### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by schuroff** [JelenaBanjac/microbiome-toolbox#4]
Dear all, 
I'm trying to install the microbiome tool-box. First, I created the environment using the command below with the provided file.

#conda env create -f Environment.yml 

But I got the following error:

**Pip subprocess error:
  ERROR: Command errored out with exit status 1:
   command: /home/microbiota/anaconda3/envs/microbiome_toolbox/bin/python /home/microbiota/anaconda3/envs/microbiome_toolbox/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mj8cmvrh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 64.0' wheel jupyterlab 'conan (>=1.57, <=1.59)'
       cwd: None
  Complete output (2 lines):
  ERROR: Could not find a version that satisfies the requirement setuptools>=64.0 #**

If I ignore this error and continue the installation another error is followed after the command:

#pip install microbiome-toolbox --user

**ERROR: Could not find a version that satisfies the requirement pythreejs>=2.4.0 (from ipyvolume->microbiome-toolbox) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.2.0b1, 0.2.0b2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.4.0a0, 0.4.0, 0.4.1, 1.0.0b0, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0, 1.1.0, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3.0)
ERROR: No matching distribution found for pythreejs>=2.4.0 (from ipyvolume->microbiome-toolbox)**

I tried installing in different computers and updated the Conda version. Also, I installed the programs setuptools >= 64.0 and pythreejs>=2.4.0, but these errors persisted.
Can you help me?

**Comment by JelenaBanjac** [comment]
Hi @schuroff,

Thanks for reporting an issue. The package versions were not explicitly indicated so it caused package conflicts. I modified the way the installation is done, now you won’t need conda.

Could you please check the code on [‘fix-installation’ branch](https://github.com/JelenaBanjac/microbiome-toolbox/blob/fix-installation) and setup the environment as indicated in the README there, [Installation](https://github.com/JelenaBanjac/microbiome-toolbox/blob/fix-installation/README.md#installation) section? 

Let me know if this works for you.

**Comment by schuroff** [comment]
Hi @JelenaBanjac,

Thanks for your reply. This time I could advance with the installation, however now I am getting the following error during the 
execution of the comand `python webapp/index.py`:
 
 Traceback (most recent call last):
  File "/home/paulo/microbiome-toolbox-fix-installation/webapp/index.py", line 1, in <module>
    from app import app, server
  File "/home/paulo/microbiome-toolbox-fix-installation/webapp/app.py", line 9, in <module>
    from environment.settings import UPLOAD_FOLDER_ROOT
  File "/home/paulo/microbiome-toolbox-fix-installation/webapp/environment/settings.py", line 12, in <module>
    APP_PORT = int(os.environ.get("PORT"))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

I guess that the "PORT" are returning an empty value. Can you help how to fix this?

Thank you!

**Comment by JelenaBanjac** [comment]
Hi @schuroff,

It seems the environment variables are not set. Have you sourced the environment variables file (i.e. command [here](https://github.com/JelenaBanjac/microbiome-toolbox/blob/fix-installation/README.md#run-dashboard-locally-on-your-computer))? 

You can then check if the environment variable PORT was set by running `echo $PORT`. It should return `8085`.

**Comment by schuroff** [comment]
Hi @JelenaBanjac 

Yes, I sourced the environment variables file.  When I check the environment variable PORT return 8085.

In my index.py file I have the following script: 

**from app import app, server
from environment.settings import APP_DEBUG, APP_HOST, APP_PORT, DEV_TOOLS_PROPS_CHECK
from pages.home.home_callbacks import *
from pages.page1.page1_callbacks import *
from pages.page2.page2_callbacks import *
from pages.page3.page3_callbacks import *
from pages.page4.page4_callbacks import *
from pages.page5.page5_callbacks import *
from pages.page6.page6_callbacks import *
from routes import render_page_content

if __name__ == "__main__":
    app.run_server(
        host=APP_HOST,
        port=APP_PORT,
        debug=APP_DEBUG,
        dev_tools_props_check=DEV_TOOLS_PROPS_CHECK,
    )**

Is it correct? 

Do I need to manually change my host, port, debug or dev_tools_props_check in my index.py file?

Thanks for your help!

**Comment by JelenaBanjac** [comment]
Hi @schuroff,

Yes, it will essentially work if you manually change all the variables. However, the environment files are created this way mainly for the purposes of quick switching between deployment and development environments. 

Could you please try to run `set -a` command before running source command?

**Comment by schuroff** [comment]
Hi @JelenaBanjac 

I used the command `set -a` before running source command. 
I was able to move forward and didn't get the previously mentioned error.

Now, when I run the command `python webapp/index.py` and I have the following output result:


**/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
Dash is running on http://127.0.0.1:8085/

 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/paulo/microbiome-toolbox-fix-installation/venv/lib/python3.10/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()**

I would like to know if this is correct or another error because I received the following message:
**WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.**

**Comment by JelenaBanjac** [comment]
Hi @schuroff,

You should be able to open the dashboard in your browser now by clicking the URL from the messages: http://127.0.0.1:8085/ Can you confirm?
The messages are not errors, just a deprication warnings from numba package. It shouldn't affect the dashboard.

**Comment by schuroff** [comment]
Hi @JelenaBanjac,

Yes, I was able to open the dashboard in my browser. Now, the program is running correctly.
Thank you very much for your help!

Best, 
Paulo

**Comment by JelenaBanjac** [comment]
Great, happy to hear that! :)
