### ISSUE TITLE
Data Formatting

### ISSUE THREAD

**Issue by ctparsons** [JelenaBanjac/microbiome-toolbox#7]
I am having some trouble getting my own data into the software, do you have an example .csv you could share, thanks in advance

**Comment by JelenaBanjac** [comment]
Hi @ctparsons,

There are two examples in the repository: [mice dataset](https://github.com/JelenaBanjac/microbiome-toolbox/blob/main/notebooks/Mouse_16S/INPUT_FILES/website_mousedata.csv) and [human dataset](https://github.com/JelenaBanjac/microbiome-toolbox/blob/main/notebooks/Human_Subramanian/INPUT_FILES/subramanian_et_al_l2_ELM_website.csv).

Hope this helps.

**Comment by ctparsons** [comment]
@JelenaBanjac 
That was just what I needed, everything appears to be working well now, thank you.
